# -*- coding: utf-8 -*-
"""Gozluk reçete hesaplayici eye glass prescription calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyp70jtLFhGK2puY4NatEBl9CQ7L-OQt
"""

def gozluk_recete_hesapla(sph, cyl, ax):
    """
    Gözlük reçetesi hesaplamak için basit bir fonksiyon.

    Args:
        sph (float): Sferik değer.
        cyl (float): Silindir değer.
        ax (int): Aks değeri.

    Returns:
        str: Tahmini gözlük reçetesi formatında bir string.
    """
    # Basit bir formata getirme
    recete = f"{sph:.2f} {cyl:.2f} x {ax}"
    return recete

# Kullanıcıdan girdi alma
sph = float(input("Sağ göz Sph (sferik) değerini girin (Örn: -1.00 veya 0.50): "))
cyl = float(input("Sağ göz Cyl (silindir) değerini girin (Örn: -0.50 veya 0.00): "))
ax = int(input("Sağ göz Aks değerini girin (0-180 derece arası, Örn: 180): "))

# Reçeteyi hesapla ve yazdır
recete = gozluk_recete_hesapla(sph, cyl, ax)
print("\nTahmini O.D. Gözlük Reçetesi:", recete)

print("\nLütfen bu sonucun sadece bir tahmin olduğunu unutmayın. "
      "Göz sağlığınız için mutlaka bir göz doktoruna danışınız.")